# Generated by Django 6.0.7 on 2026-08-05 05:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('students', '0001_initial'),
        ('teachers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('subject', models.CharField(choices=[('MATH', 'Mathematics'), ('SCI', 'Science'), ('ENG', 'English'), ('HIST', 'History'), ('ART', 'Art'), ('PE', 'Physical Education')], max_length=4)),
                ('room_number', models.CharField(blank=True, max_length=10)),
                ('schedule', models.CharField(blank=True, max_length=100)),
                ('start_date', models.DateField()),
                ('students', models.ManyToManyField(blank=True, related_name='classes', to='students.student')),
                ('teacher', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='classes', to='teachers.teacher')),
            ],
        ),
    ]
